version: '3.8'

services:
  app:
    image: neha799/flight
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/airline
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pass@word1
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: airline
      MYSQL_ROOT_PASSWORD: pass@word1
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s

volumes:
  mysql-data: